# docker-compose.yml
version: '2'

services:
  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: shellcode
      MYSQL_USER: shellcode
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  adminer:
    image: adminer
    restart: always
  node:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "8081"
    command: "npm start"
    links:
      - db