# docker-compose.yml
version: '2'

services:
  db:
    environment:
      MYSQL_ROOT_PASSWORD: <your root password>
      MYSQL_PASSWORD: <your user password>
    ports:
      - 3306:3306
  adminer:
    ports:
      - 8080:8080
