# docker-compose.yml
version: '2'

services:
  db:
    container_name: shellbot-db
    image: mariadb
    environment:
      MYSQL_DATABASE: shellcode
      MYSQL_USER: shellcode
    volumes:
      - ./.data/database:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  adminer:
    image: adminer
    restart: always
  node:
    container_name: shellbot-node
    build: docker/node
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    links:
      - db
